version: '3'

volumes:
  postgres_data:

networks:
    backend:
    frontend:

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile.pub
    image: backend
    restart: always
    ports:
      - "4000:3001"
    env_file:
      - ./.env
    networks:
      - backend
    depends_on:
      - postgres
    
  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile.pub
    image: frontend
    ports: 
      - "8080:80"
    env_file:
      - ./.env
    networks:
      - frontend

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes: 
      - postgres_data:/data/postgres
    networks:
      - backend
      
  adminer:
    image: adminer
    restart: always
    ports: 
      - '8081:8080'
    networks:
      - backend
    depends_on:
      - postgres
  
  