version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    env_file:
      - ./.env
    
  frontend:
    container_name:  frontend
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:3000"
    env_file:
      - ./.env

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
      
  adminer:
    image: adminer
    restart: always
    ports: 
      - '8081:8080'